alias vim="nvim"
alias preview="fzf --preview 'bat --color \"always\" {}'"
alias ls="ls -GwF"
alias be="bundle exec"
alias programming="cd ~/programming"
alias gst="git status"
alias k="kubectl"
alias gpom="git push origin master"
alias gl="git log"
alias glo="git log --pretty=oneline"
alias glu="git log --pretty=format:'%h %ad | %s%d [%an]' --graph --date=short"
alias glg="git log --decorate --graph --abbrev-commit --date=relative"
alias mft="mix format 'apps/*/{lib,config,test}/**/*.{ex,exs}'"
alias web="cd ~/programming/connect-web"
alias mobile="cd ~/programming/connect-web/mobile"
