export ZSH="$HOME/.oh-my-zsh"
export ZSH_CUSTOM="$HOME/dotfiles/oh-my-zsh/zsh_custom"
export PATH=$HOME/bin:/usr/local/bin:$PATH

plugins=(
  gitfast
  git-auto-fetch
  docker
  direnv
  terraform
  tmux
  fzf
  asdf
  autojump
  aliases
  exports
  rbenv
)
ZSH_THEME="sorin"
HYPHEN_INSENSITIVE="true"
DISABLE_AUTO_TITLE="true"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
ZSH_TMUX_AUTOSTART="false"
ZSH_TMUX_AUTOSTART_ONCE= "false"
ZSH_TMUX_AUTOQUIT="true"
ZSH_TMUX_AUTOCONNECT="true"

source $ZSH/oh-my-zsh.sh
export MANPATH="/usr/local/man:$MANPATH"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
