export ZSH="$HOME/.oh-my-zsh"
export ZSH_CUSTOM="$HOME/dotfiles/oh-my-zsh/zsh_custom"
export PATH=$HOME/bin:/usr/local/bin:$PATH

plugins=(
  gitfast
  direnv
  tmux
  fzf
  asdf
  aliases
  exports
  rbenv
)
ZSH_THEME="sorin"
HYPHEN_INSENSITIVE="true"
DISABLE_AUTO_TITLE="true"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
ZSH_TMUX_AUTOSTART="false"
ZSH_TMUX_AUTOSTART_ONCE= "false"
ZSH_TMUX_AUTOQUIT="true"
ZSH_TMUX_AUTOCONNECT="true"

export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH="$PATH:`pwd`/flutter/bin"

source $ZSH/oh-my-zsh.sh
export MANPATH="/usr/local/man:$MANPATH"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
